#!/bin/bash -l
#SBATCH --partition=medium
#SBATCH --tasks-per-node=32
#SBATCH --time=00:20:00
#SBATCH --account=classes
#SBATCH --mail-user=$viviiv14@wfu.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --nodes=2
#SBATCH -J prtcls2
#SBATCH -o prtcls2.%j.out
#SBATCH -e prtcls2.%j.err

cd /deac/classes/csc726/$USER/particle-simulation-part-2-esteira2
filename="mpi2-${SLURM_JOB_ID}.txt"

# set up environment
module load rhel7/openmpi/4.0.2-gcc-4.8

# run simulation for up to 64 MPI processes (32 per node)
mpirun -n 64 ./mpi -n 2000 -no -s summary-mpi.txt
